on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

name: "Build & Release"

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v3

      # Set up Java with Zulu OpenJDK 11
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      # Set up Flutter environment
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # Install dependencies and build APK for Android
            # Step 3: Flutter Clean and Dependency Install
      - name: Flutter clean and pub get
        run: |
          flutter clean
          flutter pub get

      # Build iOS app without code signing and package it
      - name: Build iOS App
        run: |
          cd ios
          pod install
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cp -R Runner.app Payload/
          zip -r app.ipa Payload

      # Upload artifacts to GitHub Releases
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk,build/ios/iphoneos/app.ipa"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
